// Generated by CoffeeScript 1.7.1
(function() {
  Showcase.ShowComponentsWellController = Ember.Controller.extend({
    wellClick: function() {
      return alert("Hello from controller: A click in a well!");
    }
  });

}).call(this);
