// Generated by CoffeeScript 1.7.1
(function() {
  Showcase.ShowComponentsButtonController = Ember.Controller.extend({
    isButtonDisabled: false,
    loadingState: null,
    loadingState1: null,
    actions: {
      disableButton: function() {
        return this.set('isButtonDisabled', true);
      },
      startLoading: function() {
        this.set('loadingState', 'loading');
        return Ember.run.later((function(_this) {
          return function() {
            return _this.set('loadingState', null);
          };
        })(this), 2000);
      },
      startLoading1: function() {
        this.set('loadingState1', 'loading');
        return Ember.run.later((function(_this) {
          return function() {
            return _this.set('loadingState1', 'completed');
          };
        })(this), 2000);
      },
      buttonWithParam: function(expectedMyself) {
        return alert("Passed controller as a param: " + expectedMyself);
      }
    }
  });

}).call(this);
