// Generated by CoffeeScript 1.7.1
(function() {
  var Bootstrap, Showcase;

  Bootstrap = window.Bootstrap;

  Showcase = window.Showcase = Ember.Application.create({
    LOG_TRANSITIONS: true,
    LOG_VIEW_LOOKUPS: true,
    LOG_ACTIVE_GENERATION: true
  });

  Ember.ENV = {
    HELPER_PARAM_LOOKUPS: true
  };

  Ember.Handlebars.registerHelper('raw', function(value) {
    return value.fn(value);
  });

  require('scripts/showcase/router');

  require('scripts/showcase/routes/*');

  require('scripts/showcase/controllers/*');

}).call(this);
