// Generated by CoffeeScript 1.7.1
(function() {
  Bootstrap.BsAlertComponent = Ember.Component.extend(Bootstrap.TypeSupport, {
    classNames: ['alert'],
    classNameBindings: ['fade', 'fade:in'],
    layoutName: 'components/bs-alert',
    classTypePrefix: 'alert',
    attributeBindings: ['data-timeout'],
    dismissAfter: 0,
    didInsertElement: function() {
      if (this.dismissAfter > 0) {
        Ember.run.later(this, 'dismiss', this.dismissAfter * 1000);
      }
      Ember.$("#" + this.elementId).bind('closed.bs.alert', (function(_this) {
        return function() {
          _this.sendAction('closed');
          return _this.destroy();
        };
      })(this));
      return Ember.$("#" + this.elementId).bind('close.bs.alert', (function(_this) {
        return function() {
          return _this.sendAction('close');
        };
      })(this));
    },
    dismiss: function() {
      return Ember.$("#" + this.elementId).alert('close');
    }
  });

  Ember.Handlebars.helper('bs-alert', Bootstrap.BsAlertComponent);

}).call(this);
