// Generated by CoffeeScript 1.7.1
(function() {
  Bootstrap.BsProgressbarComponent = Ember.Component.extend(Bootstrap.TypeSupport, {
    layoutName: 'components/bs-progressbar',
    classNames: ['progress-bar'],
    attributeBindings: ['style', 'role', 'aria-valuemin', 'ariaValueNow:aria-valuenow', 'aria-valuemax'],
    classTypePrefix: 'progress-bar',
    role: 'progressbar',
    'aria-valuemin': 0,
    'aria-valuemax': 100,
    init: function() {
      return this._super();
    },
    style: (function() {
      return "width:" + this.progress + "%;";
    }).property('progress').cacheable(),
    ariaValueNow: (function() {
      return this.progress;
    }).property('progress').cacheable()
  });

  Ember.Handlebars.helper('bs-progressbar', Bootstrap.BsProgressbarComponent);

}).call(this);
