// Generated by CoffeeScript 1.7.1
(function() {
  Bootstrap.BsTabsPanes = Bootstrap.ItemsPanesView.extend({
    classNames: ['tab-content'],
    itemViewClass: Bootstrap.BsTabPane
  });

  Ember.Handlebars.helper('bs-tabs-panes', Bootstrap.BsTabsPanes);

}).call(this);
