// Generated by CoffeeScript 1.7.1
(function() {
  Bootstrap.BsTabs = Bootstrap.ItemsView.extend(Bootstrap.Nav, {
    navType: 'tabs',
    classNameBindings: ['justified:nav-justified'],
    attributeBindings: ['style'],
    itemViewClass: Bootstrap.BsPill
  });

  Ember.Handlebars.helper('bs-tabs', Bootstrap.BsTabs);

}).call(this);
