// Generated by CoffeeScript 1.7.1

/*
A Mixin that provides the basic configuration for rendering and interacting with Bootstrap navigation item such a pill or a tab.
 */

(function() {
  Bootstrap.NavItem = Ember.Mixin.create(Bootstrap.SelectableView);

}).call(this);
